### ISSUE TITLE
sensor_pods data isn't being displayed

### ISSUE THREAD

**Issue by tinobedi** [KraigM/homebridge-wink#27]
The three sensor_pods around the my house are reporting data to homebridge but the data isn't being displayed in the correct parameters even though it shows it as a device (blank data field).

**Comment by pdlove** [comment]
@tinobedi What app on the phone are you using to display the information?

**Comment by tinobedi** [comment]
I've used a few apps and here are the results

Devices - no data displayed
Insteon+ - data displays but not in an obvious place
Home - data displays but only humility is in an obvious placement.


Home works the best because it displays all the data but I can't get Siri to tell me the temperature, or humility on request.

**Comment by tinobedi** [comment]
Here is some screenshots.

Devices: http://this.rent/pod/devices.png
Insteon+: http://this.rent/pod/Insteon_1.png, http://this.rent/pod/Insteon_2.png
Home: http://this.rent/pod/home_1.png, http://this.rent/pod/home_2.png

**Comment by pdlove** [comment]
I think alot of your issue is that Apple developers haven't figured out how to consume the sensor information yet. I recommend you look up the Eve app. In my opinion, it has the most logical display of accessories with all of the information of any app I've looked at. If that doesn't look right to you, let me know and we'll see what we need to do to fix it up. Other than that, feel free to direct your request to any of the app makers you mentioned to fix their product for a more meaningful display of information.

**Comment by tinobedi** [comment]
i'll contact the home developer but how do i ask siri for temp info?

**Comment by pdlove** [comment]
You ask Siri the Temperature in your room.
For example, I have a temperature sensor that I've added to the HomeKit room called "Kitchen"
I say "What is the Temperature in the Kitchen?"

**Comment by tinobedi** [comment]
Here's my setting because I have a few devices and I can't give repeat names.

Pods name: Bedroom Sensor
Service name: Bedroom temperature

"What is the Bedroom temperature in the Bedroom Sensor?"


That didn't work at all, what might be the issue?

**Comment by pdlove** [comment]
Have you setup rooms and added your devices into the appropriate room? It's not really looking for the device name there, it's looking for the name of a Room, not the actual accessory.
HomeKit exposes the Accessories and then you have to establish the hierarchy. It should be setup as Home>Zone>Room>Accessory. Zone can be omitted if you only need one zone. I have Upstairs and Downstairs zones so I can as the Upstairs Temperature and Downstairs Temperature and it will report based on the sensors in the zones.

**Comment by tinobedi** [comment]
I'll try this now and report back my results today

**Comment by pdlove** [comment]
Make sure you don't ask for the specific device. Make sure you ask the temperature in the room.

**Comment by tinobedi** [comment]
Yep, That's what I'm doing. Oddly, the humidity shows via siri but not temperature.

**Comment by tinobedi** [comment]
@pdlove, solved.

The issue was in naming the rooms, as you said. I changed the name from bedroom to dorm, restarted homebridge and everything is working now. I appreciate you help! 

Though do take it into consideration to separate temp, hum, battery, motion/light into their own devices. So we can see what's going on in our desired homekit apps.

**Comment by pdlove** [comment]
Siri does get confused by device names.
My kitchen has two temperature devices. When I ask for the temperature, it replies "The temperature is 61.5 and 61.7" if there is a difference, otherwise it just replies with a single temperature response.
When I ask for my downstairs temperature, Siri replies with a single number that is the average of the 8 devices downstairs.

**Comment by KraigM** [comment]
Sounds like this is resolved so I'm going to close it.  Feel free to reopen if I was wrong.
