### ISSUE TITLE
Integration of Binary Wall Switches

### ISSUE THREAD

**Issue by Jborn4christ** [KraigM/homebridge-wink#5]
Are there plans or development to add support of switches? I have a couple of the Levityon binary switches Id like to be able to use.

**Comment by davidgruhin** [comment]
Seconded!

**Comment by earlthesquirrel** [comment]
Third!

**Comment by earlthesquirrel** [comment]
I'd also say supporting general switches (i.e. I have GE Z-Wave Wall switches, GE in-wall z-wave plugs and Z-Wave plug in wall adapters.)  All of the examples given show up on Wink as binary switches.

**Comment by KraigM** [comment]
@pdlove ETA?  Can you push what you have done so far to a branch (even if it is broken) so others can pick up where you left off and help?

**Comment by pdlove** [comment]
Sorry for the delay, I'll publish my work tonight. It'll have the garage door and the binary switches. Only think that I'll be adding past that is the thermostat.

**Comment by earlthesquirrel** [comment]
Any update when this will get pushed?  You said "tonight", not sure when
that is, don't see it as of now..

EarlthSquirrel

**Comment by AppleTechy** [comment]
@pdlove do you have an update when you will be publishing your work? Thanks for your help!

**Comment by pdlove** [comment]
I just published the work I've been doing to my fork. I have some fairly significant changes that modularize this plugin a bit better to make it easier to expand. This has not been put into KraigM's repository yet and is not yet available from npm, but feel free to pull my code down and try it out. I apologize it took as long as it did to get it committed.
If someone can let me know if it works for them then I'll request it be merged with the main repository. I do still have some cleanup work to do on what I have out there so far because I'm not 100% satisfied with the quality or completeness of my work.

**Comment by KraigM** [comment]
@pdlove Create a pull request and then comments can be made, notes can be written on how to test it early, etc.

**Comment by pdlove** [comment]
Thanks for helping me through this. We use Team Foundation Server at work, so I'm still new to how the workflow goes with github.

**Comment by AppleTechy** [comment]
nfarina/homebridge#423

**Comment by pdlove** [comment]
Wall switches and Outlink are included in PR #11.

**Comment by KraigM** [comment]
Released under 1.0.0/1.0.1

**Comment by robertvorthman** [comment]
HomeKit and Wink see my GE Z-Wave wall switch as a light bulb.  Does anybody know what settings I can change to make HomeKit categorize my switch as a binary switch and not a light?  I have a white noise machine plugged into this switched outlet, and when I tell Siri to "turn off the lights" I don't want the white noise machine to turn off.
